import type { FormationSlot } from '../types'

/** Slot order is engine-relevant (role grouping); x/y are % coordinates on a
 *  vertical pitch — own goal at the bottom (y≈90), attack towards the top. */
export const FORMATIONS: Record<string, FormationSlot[]> = {
  '4-3-3': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'RB', x: 84, y: 70 },
    { role: 'DF', label: 'CB', x: 62, y: 76 },
    { role: 'DF', label: 'CB', x: 38, y: 76 },
    { role: 'DF', label: 'LB', x: 16, y: 70 },
    { role: 'MF', label: 'CM', x: 72, y: 50 },
    { role: 'MF', label: 'CM', x: 50, y: 56 },
    { role: 'MF', label: 'CM', x: 28, y: 50 },
    { role: 'FW', label: 'RW', x: 80, y: 26 },
    { role: 'FW', label: 'ST', x: 50, y: 18 },
    { role: 'FW', label: 'LW', x: 20, y: 26 },
  ],
  '4-4-2': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'RB', x: 84, y: 70 },
    { role: 'DF', label: 'CB', x: 62, y: 76 },
    { role: 'DF', label: 'CB', x: 38, y: 76 },
    { role: 'DF', label: 'LB', x: 16, y: 70 },
    { role: 'MF', label: 'RM', x: 84, y: 46 },
    { role: 'MF', label: 'CM', x: 62, y: 52 },
    { role: 'MF', label: 'CM', x: 38, y: 52 },
    { role: 'MF', label: 'LM', x: 16, y: 46 },
    { role: 'FW', label: 'ST', x: 62, y: 22 },
    { role: 'FW', label: 'ST', x: 38, y: 22 },
  ],
  '4-2-3-1': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'RB', x: 84, y: 70 },
    { role: 'DF', label: 'CB', x: 62, y: 76 },
    { role: 'DF', label: 'CB', x: 38, y: 76 },
    { role: 'DF', label: 'LB', x: 16, y: 70 },
    { role: 'MF', label: 'DM', x: 62, y: 58 },
    { role: 'MF', label: 'DM', x: 38, y: 58 },
    { role: 'MF', label: 'RAM', x: 80, y: 38 },
    { role: 'MF', label: 'CAM', x: 50, y: 34 },
    { role: 'MF', label: 'LAM', x: 20, y: 38 },
    { role: 'FW', label: 'ST', x: 50, y: 16 },
  ],
  '3-5-2': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'CB', x: 72, y: 76 },
    { role: 'DF', label: 'CB', x: 50, y: 79 },
    { role: 'DF', label: 'CB', x: 28, y: 76 },
    { role: 'MF', label: 'RWB', x: 88, y: 50 },
    { role: 'MF', label: 'CM', x: 66, y: 52 },
    { role: 'MF', label: 'CM', x: 50, y: 58 },
    { role: 'MF', label: 'CM', x: 34, y: 52 },
    { role: 'MF', label: 'LWB', x: 12, y: 50 },
    { role: 'FW', label: 'ST', x: 62, y: 22 },
    { role: 'FW', label: 'ST', x: 38, y: 22 },
  ],
  '5-3-2': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'RWB', x: 88, y: 64 },
    { role: 'DF', label: 'CB', x: 70, y: 76 },
    { role: 'DF', label: 'CB', x: 50, y: 79 },
    { role: 'DF', label: 'CB', x: 30, y: 76 },
    { role: 'DF', label: 'LWB', x: 12, y: 64 },
    { role: 'MF', label: 'CM', x: 70, y: 46 },
    { role: 'MF', label: 'CM', x: 50, y: 52 },
    { role: 'MF', label: 'CM', x: 30, y: 46 },
    { role: 'FW', label: 'ST', x: 62, y: 22 },
    { role: 'FW', label: 'ST', x: 38, y: 22 },
  ],
  '4-1-4-1': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'RB', x: 84, y: 70 },
    { role: 'DF', label: 'CB', x: 62, y: 76 },
    { role: 'DF', label: 'CB', x: 38, y: 76 },
    { role: 'DF', label: 'LB', x: 16, y: 70 },
    { role: 'MF', label: 'DM', x: 50, y: 60 },
    { role: 'MF', label: 'RM', x: 84, y: 44 },
    { role: 'MF', label: 'CM', x: 62, y: 47 },
    { role: 'MF', label: 'CM', x: 38, y: 47 },
    { role: 'MF', label: 'LM', x: 16, y: 44 },
    { role: 'FW', label: 'ST', x: 50, y: 18 },
  ],
  '4-5-1': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'RB', x: 84, y: 70 },
    { role: 'DF', label: 'CB', x: 62, y: 76 },
    { role: 'DF', label: 'CB', x: 38, y: 76 },
    { role: 'DF', label: 'LB', x: 16, y: 70 },
    { role: 'MF', label: 'RM', x: 88, y: 46 },
    { role: 'MF', label: 'CM', x: 68, y: 50 },
    { role: 'MF', label: 'CM', x: 50, y: 56 },
    { role: 'MF', label: 'CM', x: 32, y: 50 },
    { role: 'MF', label: 'LM', x: 12, y: 46 },
    { role: 'FW', label: 'ST', x: 50, y: 18 },
  ],
  '4-4-2◆': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'RB', x: 84, y: 70 },
    { role: 'DF', label: 'CB', x: 62, y: 76 },
    { role: 'DF', label: 'CB', x: 38, y: 76 },
    { role: 'DF', label: 'LB', x: 16, y: 70 },
    { role: 'MF', label: 'DM', x: 50, y: 60 },
    { role: 'MF', label: 'RCM', x: 72, y: 48 },
    { role: 'MF', label: 'LCM', x: 28, y: 48 },
    { role: 'MF', label: 'CAM', x: 50, y: 36 },
    { role: 'FW', label: 'ST', x: 62, y: 20 },
    { role: 'FW', label: 'ST', x: 38, y: 20 },
  ],
  '4-3-2-1': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'RB', x: 84, y: 70 },
    { role: 'DF', label: 'CB', x: 62, y: 76 },
    { role: 'DF', label: 'CB', x: 38, y: 76 },
    { role: 'DF', label: 'LB', x: 16, y: 70 },
    { role: 'MF', label: 'CM', x: 70, y: 52 },
    { role: 'MF', label: 'CM', x: 50, y: 58 },
    { role: 'MF', label: 'CM', x: 30, y: 52 },
    { role: 'MF', label: 'AM', x: 64, y: 34 },
    { role: 'MF', label: 'AM', x: 36, y: 34 },
    { role: 'FW', label: 'ST', x: 50, y: 16 },
  ],
  '4-2-2-2': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'RB', x: 84, y: 70 },
    { role: 'DF', label: 'CB', x: 62, y: 76 },
    { role: 'DF', label: 'CB', x: 38, y: 76 },
    { role: 'DF', label: 'LB', x: 16, y: 70 },
    { role: 'MF', label: 'DM', x: 62, y: 58 },
    { role: 'MF', label: 'DM', x: 38, y: 58 },
    { role: 'MF', label: 'RAM', x: 78, y: 38 },
    { role: 'MF', label: 'LAM', x: 22, y: 38 },
    { role: 'FW', label: 'ST', x: 62, y: 20 },
    { role: 'FW', label: 'ST', x: 38, y: 20 },
  ],
  '3-4-3': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'CB', x: 72, y: 76 },
    { role: 'DF', label: 'CB', x: 50, y: 79 },
    { role: 'DF', label: 'CB', x: 28, y: 76 },
    { role: 'MF', label: 'RM', x: 86, y: 50 },
    { role: 'MF', label: 'CM', x: 62, y: 54 },
    { role: 'MF', label: 'CM', x: 38, y: 54 },
    { role: 'MF', label: 'LM', x: 14, y: 50 },
    { role: 'FW', label: 'RW', x: 78, y: 24 },
    { role: 'FW', label: 'ST', x: 50, y: 17 },
    { role: 'FW', label: 'LW', x: 22, y: 24 },
  ],
  '3-4-2-1': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'CB', x: 72, y: 76 },
    { role: 'DF', label: 'CB', x: 50, y: 79 },
    { role: 'DF', label: 'CB', x: 28, y: 76 },
    { role: 'MF', label: 'RM', x: 86, y: 52 },
    { role: 'MF', label: 'CM', x: 62, y: 56 },
    { role: 'MF', label: 'CM', x: 38, y: 56 },
    { role: 'MF', label: 'LM', x: 14, y: 52 },
    { role: 'FW', label: 'CF', x: 64, y: 30 },
    { role: 'FW', label: 'CF', x: 36, y: 30 },
    { role: 'FW', label: 'ST', x: 50, y: 15 },
  ],
  '5-4-1': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'RWB', x: 88, y: 64 },
    { role: 'DF', label: 'CB', x: 70, y: 76 },
    { role: 'DF', label: 'CB', x: 50, y: 79 },
    { role: 'DF', label: 'CB', x: 30, y: 76 },
    { role: 'DF', label: 'LWB', x: 12, y: 64 },
    { role: 'MF', label: 'RM', x: 82, y: 46 },
    { role: 'MF', label: 'CM', x: 60, y: 50 },
    { role: 'MF', label: 'CM', x: 40, y: 50 },
    { role: 'MF', label: 'LM', x: 18, y: 46 },
    { role: 'FW', label: 'ST', x: 50, y: 18 },
  ],
  '4-1-2-1-2': [
    { role: 'GK', label: 'GK', x: 50, y: 90 },
    { role: 'DF', label: 'RB', x: 84, y: 70 },
    { role: 'DF', label: 'CB', x: 62, y: 76 },
    { role: 'DF', label: 'CB', x: 38, y: 76 },
    { role: 'DF', label: 'LB', x: 16, y: 70 },
    { role: 'MF', label: 'DM', x: 50, y: 62 },
    { role: 'MF', label: 'RCM', x: 78, y: 49 },
    { role: 'MF', label: 'LCM', x: 22, y: 49 },
    { role: 'MF', label: 'CAM', x: 50, y: 37 },
    { role: 'FW', label: 'ST', x: 62, y: 20 },
    { role: 'FW', label: 'ST', x: 38, y: 20 },
  ],
}

export const FORMATION_KEYS = Object.keys(FORMATIONS)

/** Tactical lean of the shape itself: negative = defensive, positive =
 *  attacking. Applied as a small ATT/DEF multiplier by the match engine. */
export const FORMATION_BIAS: Record<string, number> = {
  '4-3-3': 1, '4-4-2': 0, '4-2-3-1': 0, '3-5-2': 0, '5-3-2': -1,
  '4-1-4-1': -1, '4-5-1': -1, '4-4-2◆': 0, '4-3-2-1': 0, '4-2-2-2': 1,
  '3-4-3': 2, '3-4-2-1': 1, '5-4-1': -2, '4-1-2-1-2': 0,
}
